from random_variable import RandomVariable
from model_random_variable import ModelRandomVariable
from normal_distribution import NormalDistribution
from uniform_distribution import UniformDistribution
from posterior import Posterior

